### Criar eleitor
POST http://localhost:8080/eleitor
Content-Type: application/json

{
  "nome": "Josefina",
  "cpf": "12345678915",
  "idade": 100
}

###

### Criar candidato
POST http://localhost:8080/candidato
Content-Type: application/json

{
  "nome": "Zoião",
  "partido": "ABA",
  "categoria": "Prefeito",
  "numero": 45
}

###

### Votar
POST http://localhost:8080/voto
Content-Type: application/json

{
  "idEleitor": 12,
  "numeroCandidato": 45
}

###

### Listar blockchain
GET http://localhost:8080/blockchain

###

### Total de votos
GET http://localhost:8080/blockchain/total

###

### Ver votos por candidato
GET http://localhost:8080/blockchain/candidato/45

###

### Verificar eleitor
GET http://localhost:8080/blockchain/eleitor/12345678901


###

### Listar votos
GET http://localhost:8080/voto

###

### Buscar voto por ID
GET http://localhost:8080/voto/1

###

### Deletar voto
DELETE http://localhost:8080/voto/1

###

### Deletar voto
GET http://localhost:8080/eleitor/1